### PR TITLE
Example

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Go down to level 2*

## Solution
- *Apply example_ynh*
- *Include #8*
- *Try to fix https://ci-apps.yunohost.org/ci/job/1008*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Review by eauchat — APPROVED** [review]
Those changes seem good to me, I didn't test them but I'll trust the CI.
Thanks a lot for the improvements and fixes :)

**Comment by eauchat** [comment]
From what I understood and modifications I've seen, this PR also contains PR #8, right?
If you prefer I can merge changes and remove #8, but I let you do it if you want, since you proposed them, so you have the last word :)
Also sorry for the lack of attention, I didn't receive notifications about this repo, this should now be fixed.

**Comment by yalh76** [comment]
I've merged #8 into testing :)

**Pull request merged**
